# 3. Feature Enginerring

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os 
import sys
sys.path.append(os.path.join(os.path.abspath('..')))

In [3]:
import src.data_loading as dl
import scripts.feature_enigneering as fe

In [4]:
output_data = '../data/processed'
df = pd.read_csv(output_data + '/processed_data.csv')
df.head()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult
0,76871,36123,3957,887,4406,UGX,256,6,10,airtime,3,1000.0,1000,2018-11-15T02:18:49Z,2,0
1,73770,15642,4841,3829,4406,UGX,256,4,6,financial_services,2,-20.0,20,2018-11-15T02:19:08Z,2,0
2,26203,53941,4229,222,4683,UGX,256,6,1,airtime,3,500.0,500,2018-11-15T02:44:21Z,2,0
3,380,102363,648,2185,988,UGX,256,1,21,utility_bill,3,20000.0,21800,2018-11-15T03:32:55Z,2,0
4,28195,38780,4841,3829,988,UGX,256,4,6,financial_services,2,-644.0,644,2018-11-15T03:34:21Z,2,0

1. Create Aggregate Features

In [24]:
# Total transaction amount 
df['TotalTransactionAmount'] = df.groupby('CustomerId')['Value'].transform('sum')

In [6]:
# df['TotalT'] = df['CustomerId'].map(df.groupby('CustomerId')['Amount'].apply(lambda x: x.abs().sum()))

In [25]:
# Average Transaction Amount
df['AverageTransactionAmount'] = df['CustomerId'].map(df.groupby('CustomerId')['Amount'].apply(lambda x: x.abs().mean()))

In [8]:
# df['ava'] = df.groupby('CustomerId')['Value'].transform('mean')

In [26]:
# Transaction Count
df['TransationCount'] = df.groupby('CustomerId')['TransactionId'].transform('size')

Note that the std function will calculate the population standard deviation by default. So i want to calculate the sample standard deviation, so i can use the ddof parameter:

In [27]:
# Standard Deviation of Transaction Amounts
df['StdTransactionAmount'] = df['CustomerId'].map(df.groupby('CustomerId')['Amount'].apply(lambda x: x.abs().std(ddof=1)))

In [14]:
# df['StdDevTransaction'] = df.groupby('CustomerId')['Value'].transform('std')

In [ ]:
#categorical and numerical columns into variables
num_col = df.select_dtypes(include=np.number).columns
cat_col = df.select_dtypes(exclude=np.number).columns

In [30]:
import pandas as pd
import numpy as np

# Apply the function
fe.extract_features(df, ['TransactionStartTime'])

In [34]:
pd.set_option('display.max_columns', None)
df.sample(6)

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,TotalTransactionAmount,AverageTransactionAmount,TransationCount,StdTransactionAmount,StdDevTransaction,TransactionStartTimeMonth,TransactionStartTimeDay,TransactionStartTimeDayOfWeek,TransactionStartTimeDayOfYear,TransactionStartTime_Month,TransactionStartTime_Week,TransactionStartTime_Day,TransactionStartTime_Dayofweek,TransactionStartTime_Dayofyear,TransactionStartTime_Is_month_end,TransactionStartTime_Is_month_start,TransactionStartTime_Is_quarter_end,TransactionStartTime_Is_quarter_start,TransactionStartTime_Is_year_end,TransactionStartTime_Is_year_start,TransactionStartTime_Hour,TransactionStartTime_Minute,TransactionStartTime_Second,TransactionStartTime_Elapsed
521,34382,17374,4841,3829,1979,UGX,256,4,6,financial_services,2,-50.0,50,2018-11-15 16:36:08+00:00,2,0,319567,1761.502762,181,6881.548633,6883.390200,11,15,3,319,11,46,15,3,319,False,False,False,False,False,False,16,36,8,1542299768
66986,5647,93703,3869,3560,4315,UGX,256,6,11,data_bundles,3,2000.0,2000,2019-01-21 11:41:09+00:00,2,0,1410117,10637.651163,129,21751.295038,22439.241501,1,21,0,21,1,4,21,0,21,False,False,False,False,False,False,11,41,9,1548070869
21588,112768,35424,2850,3241,3272,UGX,256,1,10,airtime,3,900.0,900,2018-12-09 13:18:54+00:00,4,0,76424,2635.310345,29,8638.350938,8638.350938,12,9,6,343,12,49,9,6,343,False,False,False,False,False,False,13,18,54,1544361534
16617,14202,136867,4249,4429,7343,UGX,256,4,3,airtime,2,-12500.0,12500,2018-12-04 17:05:07+00:00,4,0,104900000,25641.652408,4091,12952.599898,12952.599898,12,4,1,338,12,49,4,1,338,False,False,False,False,False,False,17,5,7,1543943107
22783,42875,13384,1907,764,2301,UGX,256,6,3,airtime,3,500.0,500,2018-12-11 05:09:06+00:00,2,0,790993,3346.580085,236,9303.893615,9307.872209,12,11,1,345,12,50,11,1,345,False,False,False,False,False,False,5,9,6,1544504946
36444,106365,101730,4841,3829,2269,UGX,256,4,6,financial_services,2,-5000.0,5000,2018-12-21 19:51:20+00:00,2,0,41000,6833.333333,6,3763.863264,3763.863264,12,21,4,355,12,51,21,4,355,False,False,False,False,False,False,19,51,20,1545421880